config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("apps/", include("hyper.apps.urls", namespace="apps")),
    path("pages/", include("hyper.pages.urls", namespace="pages")),
    path("layouts/", include("hyper.layouts.urls", namespace="layouts")),
    path("ui/", include("hyper.ui.urls", namespace="ui")),
    path("extended/", include("hyper.extended.urls", namespace="extended")),
    path("icons/", include("hyper.icons.urls", namespace="icons")),
    path("form/", include("hyper.form.urls", namespace="form")),
    path("charts/", include("hyper.charts.urls", namespace="charts")),
    path("tables/", include("hyper.tables.urls", namespace="tables")),
    path("maps/", include("hyper.maps.urls", namespace="maps")),
    path("users/", include("hyper.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("dashboard/", include("hyper.dashboard.urls", namespace="dashboard")),
    path("", include("hyper.dashboard.urls", namespace="dashboard")),
    path('celery-progress/', include('celery_progress.urls'))
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

hyper/apps/urls.py
from django.urls import path

from .views import (
    apps_chat_chat_view,

    # email
    apps_email_inbox_view,
    apps_email_read_view,

    # file manager
    apps_file_manager_view,

    # projects
    apps_projects_add_view,
    apps_projects_details_view,
    apps_projects_gantt_view,
    apps_projects_list_view,

    # social
    apps_social_feed_view,

    # tasks
    apps_tasks_details_view,
    apps_tasks_kanban_view,
    apps_tasks_tasks_view,

    # calendar
    EventListView,
    EventCreateView,
    EventUpdateView,
    EventDeleteView,
    apps_calendar_calendar_view
)


app_name = "apps"
urlpatterns = [

    # calendar
    path("event/", view=EventListView.as_view(), name="event-list"),
    path("event/add/", view=EventCreateView.as_view(), name="event-add"),
    path("event/edit/<pk>", view=EventUpdateView.as_view(), name="event-edit"),
    path("event/remove/<pk>", view=EventDeleteView.as_view(), name="event-remove"),
    path("calendar", view=apps_calendar_calendar_view, name="calendar"),


    # chat
    path("chat", view=apps_chat_chat_view, name="chat"),

    # email
    path("email/inbox", view=apps_email_inbox_view, name="email.inbox"),
    path("email/read", view=apps_email_read_view, name="email.read"),

    # manager
    path("file/manager", view=apps_file_manager_view, name="manager.file.manager"),

    # projects
    path("projects/add", view=apps_projects_add_view, name="projects.add"),
    path("projects/details", view=apps_projects_details_view, name="projects.details"),
    path("projects/gantt", view=apps_projects_gantt_view, name="projects.gantt"),
    path("projects/list", view=apps_projects_list_view, name="projects.list"),

    # social
    path("social/feed", view=apps_social_feed_view, name="social.feed"),

    # tasks
    path("tasks/details", view=apps_tasks_details_view, name="tasks.details"),
    path("tasks/kanban", view=apps_tasks_kanban_view, name="tasks.kanban"),
    path("tasks/list", view=apps_tasks_tasks_view, name="tasks.tasks"),
]

hyper/dashboard/urls.py
from django.urls import path
from django.conf.urls import url
from django.views.generic.base import View
from .views import (dashboard_main_view,
                    dashboard_scan_details,
                    dashboard_cve_details,
                    dashboard_scan_view,
                    dashboard_manage_scan_view,
                    dashboard_address_view,
                    address_details_view,
                    address_cve_details_view,
                    asset_group_view,
                    asset_group_create_view,
                    asset_group_manage_view,
                    asset_group_address_view,
                    dashboard_info_view,
                    dashboard_score_view,
                    asset_group_scan_view,
                    download_view
                    )

app_name = "dashboard"
urlpatterns = [
    path("dashboard/level/<slug:score>/", view=dashboard_score_view, name="dashboard score"),
    path("dashboard/scans", view=dashboard_main_view, name="index"),
    path("", view=dashboard_info_view, name="info"),
    path("addresses", view=dashboard_address_view, name="address view"),
    path('addresses/<slug:slug>/', view=address_details_view, name="address details"),
    path('addresses/<slug:slug>/<slug:cveid>/', view=address_cve_details_view, name="address cve details"),
    path("assets/", view=asset_group_view, name="asset view"),
    path("assets/create", view=asset_group_create_view, name="create asset group"),
    path("assets/manage/<slug:groupid>/", view=asset_group_manage_view, name="manage asset group"),
    path("assets/<slug:groupid>", view=asset_group_address_view, name="group address view"),
    path("assets/<slug:groupid>/scan", view=asset_group_scan_view, name="group scan view"),
    path("download/<slug:downloadtype>/<slug:downloadvalue>", view=download_view, name="download view"),
    url(r'^scan/(?P<slug>[\w-]+)/manage/$', view=dashboard_manage_scan_view, name="manage scan"),
    url(r'^scan/(?P<slug>[\w-]+)/(?P<cveid>[\w-]+)/$', view=dashboard_cve_details, name="cve details"),
    url(r'^scan/(?P<slug>[\w-]+)/$', view=dashboard_scan_details, name="scan details"),
    url(r'^scan/$', view=dashboard_scan_view, name="scan"),
]

hyper/form/urls.py
from django.urls import path

from .views import (
form_advanced_view,
form_editors_view,
form_elements_view,
form_fileuploads_view,
form_validation_view,
form_wizard_view,

)

app_name = "form"
urlpatterns = [
    path("advanced", view=form_advanced_view,name="advanced"),
    path("editors", view=form_editors_view, name="editors"),
    path("elements", view=form_elements_view, name="elements"),
    path("fileuploads", view=form_fileuploads_view, name="fileuploads"),
    path("validation", view=form_validation_view, name="validation"),
    path("wizard", view=form_wizard_view, name="wizard"),
   
]

hyper/pages/urls.py
from django.urls import path

from .views import (
    pages_404_alt_view,
    pages_404_view,
    pages_500_view,
    pages_confirm_mail_2_view,
    pages_confirm_mail_view,
    pages_faq_view,
    pages_invoice_view,
    pages_lock_screen_2_view,
    pages_lock_screen_view,
    pages_login_2_view,
    pages_login_view,
    pages_logout_2_view,
    pages_logout_view,
    pages_maintenance_view,
    pages_preloader_view,
    pages_pricing_view,
    pages_profile_2_view,
    pages_profile_view,
    pages_recoverpw_2_view,
    pages_recoverpw_view,
    pages_register_2_view,
    pages_register_view,
    pages_starter_view,
    pages_timeline_view,
)


app_name = "pages"
urlpatterns = [
    path("404-alt", view=pages_404_alt_view, name="404-alt"),
    path("404", view=pages_404_view, name="404"),
    path("500", view=pages_500_view, name="500"),
    path("confirm-mail-2", view=pages_confirm_mail_2_view, name="confirm-mail-2"),
    path("confirm-mail", view=pages_confirm_mail_view, name="confirm-mail"),
    path("faq", view=pages_faq_view, name="faq"),
    path("invoice", view=pages_invoice_view, name="invoice"),
    path("lock-screen-2", view=pages_lock_screen_2_view, name="lock-screen-2"),
    path("lock-screen", view=pages_lock_screen_view, name="lock-screen"),
    path("login-2", view=pages_login_2_view, name="login-2"),
    path("login", view=pages_login_view, name="login"),
    path("logout-2", view=pages_logout_2_view, name="logout-2"),
    path("logout", view=pages_logout_view, name="logout"),
    path("maintenance", view=pages_maintenance_view, name="maintenance"),
    path("preloader", view=pages_preloader_view, name="preloader"),
    path("pricing", view=pages_pricing_view, name="pricing"),
    path("profile-2", view=pages_profile_2_view, name="profile-2"),
    path("profile", view=pages_profile_view, name="profile"),
    path("recoverpw-2", view=pages_recoverpw_2_view, name="recoverpw-2"),
    path("recoverpw", view=pages_recoverpw_view, name="recoverpw"),
    path("register-2", view=pages_register_2_view, name="register-2"),
    path("register", view=pages_register_view, name="register"),
    path("starter", view=pages_starter_view, name="starter"),
    path("timeline", view=pages_timeline_view, name="timeline"),
]

hyper/ui/urls.py
from django.urls import path

from .views import (
    ui_accordions_view,
    ui_alerts_view,
    ui_avatars_view,
    ui_badges_view,
    ui_breadcrumb_view,
    ui_buttons_view,
    ui_cards_view,
    ui_carousel_view,
    ui_dropdowns_view,
    ui_embed_video_view,
    ui_grid_view,
    ui_list_group_view,
    ui_modals_view,
    ui_notifications_view,
    ui_offcanvas_view,
    ui_pagination_view,
    ui_popovers_view,
    ui_progress_view,
    ui_ribbons_view,
    ui_spinners_view,
    ui_tabs_view,
    ui_tooltips_view,
    ui_typography_view,

)

app_name = "ui"
urlpatterns = [
    path("accordions", view=ui_accordions_view, name="accordions"),
    path("alerts", view=ui_alerts_view, name="alerts"),
    path("avatars", view=ui_avatars_view, name="avatars"),
    path("badges", view=ui_badges_view, name="badges"),
    path("breadcrumb", view=ui_breadcrumb_view, name="breadcrumb"),
    path("buttons", view=ui_buttons_view, name="buttons"),
    path("cards", view=ui_cards_view, name="cards"),
    path("carousel", view=ui_carousel_view, name="carousel"),
    path("dropdowns", view=ui_dropdowns_view, name="dropdowns"),
    path("embed-video", view=ui_embed_video_view, name="embed-video"),
    path("grid", view=ui_grid_view, name="grid"),
    path("list-group", view=ui_list_group_view, name="list-group"),
    path("modals", view=ui_modals_view, name="modals"),
    path("notifications", view=ui_notifications_view, name="notifications"),
    path("offcanvas", view=ui_offcanvas_view, name="offcanvas"),
    path("pagination", view=ui_pagination_view, name="pagination"),
    path("popovers", view=ui_popovers_view, name="popovers"),
    path("progress", view=ui_progress_view, name="progress"),
    path("ribbons", view=ui_ribbons_view, name="ribbons"),
    path("spinners", view=ui_spinners_view, name="spinners"),
    path("tabs", view=ui_tabs_view, name="tabs"),
    path("tooltips", view=ui_tooltips_view, name="tooltips"),
    path("typography", view=ui_typography_view, name="typography"),
]

hyper/apps/views.py
import json
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.views import View
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import get_object_or_404


from hyper.apps.models import Event
from hyper.apps.forms import EventForm



class EventListView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        events = Event.objects.all()
        events_dict = []
        for event in events:
            events_dict.append(event.to_dict())
        return HttpResponse(json.dumps(events_dict), content_type='application/json')

class EventCreateView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        form = EventForm(data=request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            save_data = {}
            save_data["title"] = cleaned_data.get("title")
            save_data["category"] = cleaned_data.get("className")
            save_data["start_date"] = cleaned_data.get("start")
            if cleaned_data.get("allDay", None):
                save_data["all_day"] = cleaned_data.get("allDay")
            if cleaned_data.get("end", None):
                save_data["end_date"] = cleaned_data.get("end")
            event = Event.objects.create(**save_data)
            return HttpResponse(json.dumps(event.to_dict()), content_type='application/json')
        return HttpResponseBadRequest(json.dumps(form.errors), content_type='application/json')

class EventUpdateView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get("pk", None)
        obj = get_object_or_404(Event, id=pk)
        form = EventForm(data=request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            obj.title = cleaned_data.get("title")
            obj.category = cleaned_data.get("className")
            obj.start_date = cleaned_data.get("start")
            obj.all_day = cleaned_data.get("allDay", None)
            obj.end_date = cleaned_data.get("end", None)
            obj.save()
            return HttpResponse(json.dumps(obj.to_dict()), content_type='application/json')
        return HttpResponseBadRequest(json.dumps(form.errors), content_type='application/json')

class EventDeleteView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get("pk", None)
        obj = get_object_or_404(Event, id=pk)
        obj.delete()
        return HttpResponse(
            json.dumps({"message" : "The event has been removed successfully."}), 
            content_type='application/json'
            )        


class AppsView(LoginRequiredMixin, TemplateView):
    pass

# calendar
apps_calendar_calendar_view = AppsView.as_view(template_name="apps/calendar/calendar.html")


class AppsView(LoginRequiredMixin, TemplateView):
    pass

#chat
apps_chat_chat_view = AppsView.as_view(template_name="apps/chat/chat.html")

# email
apps_email_inbox_view = AppsView.as_view(template_name="apps/email/inbox.html")
apps_email_read_view = AppsView.as_view(template_name="apps/email/read.html")

# file manager
apps_file_manager_view = AppsView.as_view(template_name="apps/file/manager.html")

# projects
apps_projects_add_view = AppsView.as_view(template_name="apps/projects/add.html")
apps_projects_details_view = AppsView.as_view(template_name="apps/projects/details.html")
apps_projects_gantt_view = AppsView.as_view(template_name="apps/projects/gantt.html")
apps_projects_list_view = AppsView.as_view(template_name="apps/projects/list.html")

# social
apps_social_feed_view = AppsView.as_view(template_name="apps/social/feed.html")

# tasks
apps_tasks_details_view = AppsView.as_view(template_name="apps/tasks/details.html")
apps_tasks_kanban_view = AppsView.as_view(template_name="apps/tasks/kanban.html")
apps_tasks_tasks_view = AppsView.as_view(template_name="apps/tasks/tasks.html")

hyper/charts/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


class ChartsView(LoginRequiredMixin, TemplateView):
    pass



charts_sbrite_view = ChartsView.as_view(template_name="charts/brite.html")
charts_chartjs_view = ChartsView.as_view(template_name="charts/chartjs.html")
charts_sparkline_view = ChartsView.as_view(template_name="charts/sparkline.html")
charts_apex_area_view = ChartsView.as_view(template_name="charts/apex/area.html")
charts_apex_bar_view = ChartsView.as_view(template_name="charts/apex/bar.html")
charts_apex_bubble_view = ChartsView.as_view(template_name="charts/apex/bubble.html")
charts_apex_candlestick_view = ChartsView.as_view(template_name="charts/apex/candlestick.html")
charts_apex_column_view = ChartsView.as_view(template_name="charts/apex/column.html")
charts_apex_heatmap_view = ChartsView.as_view(template_name="charts/apex/heatmap.html")
charts_apex_line_view = ChartsView.as_view(template_name="charts/apex/line.html")
charts_apex_mixed_view = ChartsView.as_view(template_name="charts/apex/mixed.html")
charts_apex_pie_view = ChartsView.as_view(template_name="charts/apex/pie.html")
charts_apex_radar_view = ChartsView.as_view(template_name="charts/apex/radar.html")
charts_apex_radialbar_view = ChartsView.as_view(template_name="charts/apex/radialbar.html")
charts_apex_scatter_view = ChartsView.as_view(template_name="charts/apex/scatter.html")
charts_apex_sparklines_view = ChartsView.as_view(template_name="charts/apex/sparklines.html")

hyper/form/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

# Create your views here.



class FormView(LoginRequiredMixin, TemplateView):
    pass

form_advanced_view = FormView.as_view(template_name="form/advanced.html")
form_editors_view = FormView.as_view(template_name="form/editors.html")
form_elements_view = FormView.as_view(template_name="form/elements.html")
form_fileuploads_view = FormView.as_view(template_name="form/fileuploads.html")
form_validation_view = FormView.as_view(template_name="form/validation.html")
form_wizard_view = FormView.as_view(template_name="form/wizard.html")

hyper/templates/pages/404-alt.html
{% extends "vertical_base.html" %}
{% load static i18n %}

{% block title %}{% trans "Error 404" %}{% endblock title %}

{% block content %}
<!-- Start Content-->
<div class="container-fluid">
    
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Hyper</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Pages</a></li>
                        <li class="breadcrumb-item active">404</li>
                    </ol>
                </div>
                <h4 class="page-title">404 Error</h4>
            </div>
        </div>
    </div>     
    <!-- end page title --> 

    <div class="row justify-content-center">
        <div class="col-lg-4">
            <div class="text-center">
                <img src="{% static 'images/file-searching.svg' %}"  height="90" alt="File not found Image">

                <h1 class="text-error mt-4">404</h1>
                <h4 class="text-uppercase text-danger mt-3">Page Not Found</h4>
                <p class="text-muted mt-3">It's looking like you may have taken a wrong turn. Don't worry... it
                    happens to the best of us. Here's a
                    little tip that might help you get back on track.</p>

                <a class="btn btn-info mt-3" href="{% url 'dashboard:index' %}"><i class="mdi mdi-reply"></i> Return Home</a>
            </div> <!-- end /.text-center-->
        </div> <!-- end col-->
    </div>
    <!-- end row -->
    
</div> <!-- container -->
{% endblock %}

hyper/templates/pages/lock-screen.html
{% extends "account/base.html" %}
{% load static i18n %}

{% block title %}{% trans "Lock Screen" %}{% endblock title %}

{% block body_extra %}
class="loading authentication-bg" data-layout-config='{"leftSideBarTheme":"dark","layoutBoxed":false, "leftSidebarCondensed":false, "leftSidebarScrollable":false,"darkMode":false, "showRightSidebarOnStart": true}'
{% endblock %}

{% block page_content %}
<div class="account-pages pt-2 pt-sm-5 pb-4 pb-sm-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xxl-4 col-lg-5">
                <div class="card">
                    <!-- Logo -->
                    <div class="card-header pt-4 pb-4 text-center bg-primary">
                        <a href="{% url 'dashboard:index' %}">
                            <span><img src="{% static 'images/logo.png' %}"  alt="" height="18"></span>
                        </a>
                    </div>

                    <div class="card-body p-4">
                        
                        <div class="text-center w-75 m-auto">
                            <img src="{% static 'images/users/avatar-1.jpg' %}"  height="64" alt="user-image" class="rounded-circle shadow">
                            <h4 class="text-dark-50 text-center mt-3 fw-bold">Hi ! Michael </h4>
                            <p class="text-muted mb-4">Enter your password to access the admin.</p>
                        </div>

                        <form action="#">
                            <div class="mb-3">
                                <label for="password" class="form-label">Password</label>
                                <input class="form-control" type="password" required="" id="password" placeholder="Enter your password">
                            </div>

                            <div class="mb-0 text-center">
                                <button class="btn btn-primary" type="submit">Log In</button>
                            </div>
                        </form>
                        
                    </div> <!-- end card-body-->
                </div>
                <!-- end card-->

                <div class="row mt-3">
                    <div class="col-12 text-center">
                        <p class="text-muted">Not you? return <a href="{% url 'pages:login' %}" class="text-muted ms-1"><b>Sign In</b></a></p>
                    </div> <!-- end col -->
                </div>
                <!-- end row -->

            </div> <!-- end col -->
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</div>
<!-- end page -->

<footer class="footer footer-alt">
    2018 - 2021 © Hyper - Coderthemes.com
</footer>
{% endblock %}

hyper/templates/pages/login-2.html
{% extends "account/base.html" %}
{% load static i18n %}

{% block title %}{% trans "Log In" %}{% endblock title %}

{% block body_extra %}
class="authentication-bg pb-0" data-layout-config='{"darkMode":false}'
{% endblock %}

{% block page_content %}
<div class="auth-fluid">
    <!--Auth fluid left content -->
    <div class="auth-fluid-form-box">
        <div class="align-items-center d-flex h-100">
            <div class="card-body">

                <!-- Logo -->
                <div class="auth-brand text-center text-lg-start">
                    <a href="{% url 'dashboard:index' %}" class="logo-dark">
                        <span><img src="{% static 'images/logo-dark.png' %}"  alt="" height="18"></span>
                    </a>
                    <a href="{% url 'dashboard:index' %}" class="logo-light">
                        <span><img src="{% static 'images/logo.png' %}"  alt="" height="18"></span>
                    </a>
                </div>

                <!-- title-->
                <h4 class="mt-0">Sign In</h4>
                <p class="text-muted mb-4">Enter your email address and password to access account.</p>

                <!-- form -->
                <form action="#">
                    <div class="mb-3">
                        <label for="emailaddress" class="form-label">Email address</label>
                        <input class="form-control" type="email" id="emailaddress" required="" placeholder="Enter your email">
                    </div>
                    <div class="mb-3">
                        <a href="{% url 'pages:recoverpw-2' %}" class="text-muted float-end"><small>Forgot your password?</small></a>
                        <label for="password" class="form-label">Password</label>
                        <input class="form-control" type="password" required="" id="password" placeholder="Enter your password">
                    </div>
                    <div class="mb-3">
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="checkbox-signin">
                            <label class="form-check-label" for="checkbox-signin">Remember me</label>
                        </div>
                    </div>
                    <div class="d-grid mb-0 text-center">
                        <button class="btn btn-primary" type="submit"><i class="mdi mdi-login"></i> Log In </button>
                    </div>
                    <!-- social-->
                    <div class="text-center mt-4">
                        <p class="text-muted font-16">Sign in with</p>
                        <ul class="social-list list-inline mt-3">
                            <li class="list-inline-item">
                                <a href="javascript: void(0);" class="social-list-item border-primary text-primary"><i class="mdi mdi-facebook"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="javascript: void(0);" class="social-list-item border-danger text-danger"><i class="mdi mdi-google"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="javascript: void(0);" class="social-list-item border-info text-info"><i class="mdi mdi-twitter"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="javascript: void(0);" class="social-list-item border-secondary text-secondary"><i class="mdi mdi-github"></i></a>
                            </li>
                        </ul>
                    </div>
                </form>
                <!-- end form-->

                <!-- Footer-->
                <footer class="footer footer-alt">
                    <p class="text-muted">Don't have an account? <a href="{% url 'pages:register-2' %}" class="text-muted ms-1"><b>Sign Up</b></a></p>
                </footer>

            </div> <!-- end .card-body -->
        </div> <!-- end .align-items-center.d-flex.h-100-->
    </div>
    <!-- end auth-fluid-form-box-->

    <!-- Auth fluid right content -->
    <div class="auth-fluid-right text-center">
        <div class="auth-user-testimonial">
            <h2 class="mb-3">I love the color!</h2>
            <p class="lead"><i class="mdi mdi-format-quote-open"></i> It's a elegent templete. I love it very much! . <i class="mdi mdi-format-quote-close"></i>
            </p>
            <p>
                - Hyper Admin User
            </p>
        </div> <!-- end auth-user-testimonial-->
    </div>
    <!-- end Auth fluid right content -->
</div>
<!-- end auth-fluid-->
{% endblock %}

hyper/templates/pages/login.html
{% extends "account/base.html" %}
{% load static i18n %}

{% block title %}{% trans "Log In" %}{% endblock title %}

{% block body_extra %}
class="loading authentication-bg" data-layout-config='{"leftSideBarTheme":"dark","layoutBoxed":false, "leftSidebarCondensed":false, "leftSidebarScrollable":false,"darkMode":false, "showRightSidebarOnStart": true}'
{% endblock %}

{% block page_content %}
<div class="account-pages pt-2 pt-sm-5 pb-4 pb-sm-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xxl-4 col-lg-5">
                <div class="card">

                    <!-- Logo -->
                    <div class="card-header pt-4 pb-4 text-center bg-primary">
                        <a href="{% url 'dashboard:index' %}">
                            <span><img src="{% static 'images/logo.png' %}"  alt="" height="18"></span>
                        </a>
                    </div>

                    <div class="card-body p-4">
                        
                        <div class="text-center w-75 m-auto">
                            <h4 class="text-dark-50 text-center pb-0 fw-bold">Sign In</h4>
                            <p class="text-muted mb-4">Enter your email address and password to access admin panel.</p>
                        </div>

                        <form action="#">

                            <div class="mb-3">
                                <label for="emailaddress" class="form-label">Email address</label>
                                <input class="form-control" type="email" id="emailaddress" required="" placeholder="Enter your email">
                            </div>

                            <div class="mb-3">
                                <a href="{% url 'pages:recoverpw' %}" class="text-muted float-end"><small>Forgot your password?</small></a>
                                <label for="password" class="form-label">Password</label>
                                <div class="input-group input-group-merge">
                                    <input type="password" id="password" class="form-control" placeholder="Enter your password">
                                    <div class="input-group-text" data-password="false">
                                        <span class="password-eye"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="mb-3 mb-3">
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input" id="checkbox-signin" checked>
                                    <label class="form-check-label" for="checkbox-signin">Remember me</label>
                                </div>
                            </div>

                            <div class="mb-3 mb-0 text-center">
                                <button class="btn btn-primary" type="submit"> Log In </button>
                            </div>

                        </form>
                    </div> <!-- end card-body -->
                </div>
                <!-- end card -->

                <div class="row mt-3">
                    <div class="col-12 text-center">
                        <p class="text-muted">Don't have an account? <a href="{% url 'pages:register' %}" class="text-muted ms-1"><b>Sign Up</b></a></p>
                    </div> <!-- end col -->
                </div>
                <!-- end row -->

            </div> <!-- end col -->
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</div>
<!-- end page -->

<footer class="footer footer-alt">
    2018 - 2021 © Hyper - Coderthemes.com
</footer>
{% endblock %}