config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("apps/", include("hyper.apps.urls", namespace="apps")),
    path("pages/", include("hyper.pages.urls", namespace="pages")),
    path("layouts/", include("hyper.layouts.urls", namespace="layouts")),
    path("ui/", include("hyper.ui.urls", namespace="ui")),
    path("extended/", include("hyper.extended.urls", namespace="extended")),
    path("icons/", include("hyper.icons.urls", namespace="icons")),
    path("form/", include("hyper.form.urls", namespace="form")),
    path("charts/", include("hyper.charts.urls", namespace="charts")),
    path("tables/", include("hyper.tables.urls", namespace="tables")),
    path("maps/", include("hyper.maps.urls", namespace="maps")),
    path("users/", include("hyper.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("dashboard/", include("hyper.dashboard.urls", namespace="dashboard")),
    path("", include("hyper.dashboard.urls", namespace="dashboard")),
    path('celery-progress/', include('celery_progress.urls'))
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

hyper/apps/urls.py
from django.urls import path

from .views import (
    apps_chat_chat_view,

    # email
    apps_email_inbox_view,
    apps_email_read_view,

    # file manager
    apps_file_manager_view,

    # projects
    apps_projects_add_view,
    apps_projects_details_view,
    apps_projects_gantt_view,
    apps_projects_list_view,

    # social
    apps_social_feed_view,

    # tasks
    apps_tasks_details_view,
    apps_tasks_kanban_view,
    apps_tasks_tasks_view,

    # calendar
    EventListView,
    EventCreateView,
    EventUpdateView,
    EventDeleteView,
    apps_calendar_calendar_view
)


app_name = "apps"
urlpatterns = [

    # calendar
    path("event/", view=EventListView.as_view(), name="event-list"),
    path("event/add/", view=EventCreateView.as_view(), name="event-add"),
    path("event/edit/<pk>", view=EventUpdateView.as_view(), name="event-edit"),
    path("event/remove/<pk>", view=EventDeleteView.as_view(), name="event-remove"),
    path("calendar", view=apps_calendar_calendar_view, name="calendar"),


    # chat
    path("chat", view=apps_chat_chat_view, name="chat"),

    # email
    path("email/inbox", view=apps_email_inbox_view, name="email.inbox"),
    path("email/read", view=apps_email_read_view, name="email.read"),

    # manager
    path("file/manager", view=apps_file_manager_view, name="manager.file.manager"),

    # projects
    path("projects/add", view=apps_projects_add_view, name="projects.add"),
    path("projects/details", view=apps_projects_details_view, name="projects.details"),
    path("projects/gantt", view=apps_projects_gantt_view, name="projects.gantt"),
    path("projects/list", view=apps_projects_list_view, name="projects.list"),

    # social
    path("social/feed", view=apps_social_feed_view, name="social.feed"),

    # tasks
    path("tasks/details", view=apps_tasks_details_view, name="tasks.details"),
    path("tasks/kanban", view=apps_tasks_kanban_view, name="tasks.kanban"),
    path("tasks/list", view=apps_tasks_tasks_view, name="tasks.tasks"),
]

hyper/dashboard/urls.py
from django.urls import path
from django.conf.urls import url
from django.views.generic.base import View
from .views import (dashboard_main_view,
                    dashboard_scan_details,
                    dashboard_cve_details,
                    dashboard_scan_view,
                    dashboard_manage_scan_view,
                    dashboard_address_view,
                    address_details_view,
                    address_cve_details_view,
                    asset_group_view,
                    asset_group_create_view,
                    asset_group_manage_view,
                    asset_group_address_view,
                    dashboard_info_view,
                    dashboard_score_view,
                    asset_group_scan_view,
                    download_view
                    )

app_name = "dashboard"
urlpatterns = [
    path("dashboard/level/<slug:score>/", view=dashboard_score_view, name="dashboard score"),
    path("dashboard/scans", view=dashboard_main_view, name="index"),
    path("", view=dashboard_info_view, name="info"),
    path("addresses", view=dashboard_address_view, name="address view"),
    path('addresses/<slug:slug>/', view=address_details_view, name="address details"),
    path('addresses/<slug:slug>/<slug:cveid>/', view=address_cve_details_view, name="address cve details"),
    path("assets/", view=asset_group_view, name="asset view"),
    path("assets/create", view=asset_group_create_view, name="create asset group"),
    path("assets/manage/<slug:groupid>/", view=asset_group_manage_view, name="manage asset group"),
    path("assets/<slug:groupid>", view=asset_group_address_view, name="group address view"),
    path("assets/<slug:groupid>/scan", view=asset_group_scan_view, name="group scan view"),
    path("download/<slug:downloadtype>/<slug:downloadvalue>", view=download_view, name="download view"),
    url(r'^scan/(?P<slug>[\w-]+)/manage/$', view=dashboard_manage_scan_view, name="manage scan"),
    url(r'^scan/(?P<slug>[\w-]+)/(?P<cveid>[\w-]+)/$', view=dashboard_cve_details, name="cve details"),
    url(r'^scan/(?P<slug>[\w-]+)/$', view=dashboard_scan_details, name="scan details"),
    url(r'^scan/$', view=dashboard_scan_view, name="scan"),
]

hyper/form/urls.py
from django.urls import path

from .views import (
form_advanced_view,
form_editors_view,
form_elements_view,
form_fileuploads_view,
form_validation_view,
form_wizard_view,

)

app_name = "form"
urlpatterns = [
    path("advanced", view=form_advanced_view,name="advanced"),
    path("editors", view=form_editors_view, name="editors"),
    path("elements", view=form_elements_view, name="elements"),
    path("fileuploads", view=form_fileuploads_view, name="fileuploads"),
    path("validation", view=form_validation_view, name="validation"),
    path("wizard", view=form_wizard_view, name="wizard"),
   
]

hyper/ui/urls.py
from django.urls import path

from .views import (
    ui_accordions_view,
    ui_alerts_view,
    ui_avatars_view,
    ui_badges_view,
    ui_breadcrumb_view,
    ui_buttons_view,
    ui_cards_view,
    ui_carousel_view,
    ui_dropdowns_view,
    ui_embed_video_view,
    ui_grid_view,
    ui_list_group_view,
    ui_modals_view,
    ui_notifications_view,
    ui_offcanvas_view,
    ui_pagination_view,
    ui_popovers_view,
    ui_progress_view,
    ui_ribbons_view,
    ui_spinners_view,
    ui_tabs_view,
    ui_tooltips_view,
    ui_typography_view,

)

app_name = "ui"
urlpatterns = [
    path("accordions", view=ui_accordions_view, name="accordions"),
    path("alerts", view=ui_alerts_view, name="alerts"),
    path("avatars", view=ui_avatars_view, name="avatars"),
    path("badges", view=ui_badges_view, name="badges"),
    path("breadcrumb", view=ui_breadcrumb_view, name="breadcrumb"),
    path("buttons", view=ui_buttons_view, name="buttons"),
    path("cards", view=ui_cards_view, name="cards"),
    path("carousel", view=ui_carousel_view, name="carousel"),
    path("dropdowns", view=ui_dropdowns_view, name="dropdowns"),
    path("embed-video", view=ui_embed_video_view, name="embed-video"),
    path("grid", view=ui_grid_view, name="grid"),
    path("list-group", view=ui_list_group_view, name="list-group"),
    path("modals", view=ui_modals_view, name="modals"),
    path("notifications", view=ui_notifications_view, name="notifications"),
    path("offcanvas", view=ui_offcanvas_view, name="offcanvas"),
    path("pagination", view=ui_pagination_view, name="pagination"),
    path("popovers", view=ui_popovers_view, name="popovers"),
    path("progress", view=ui_progress_view, name="progress"),
    path("ribbons", view=ui_ribbons_view, name="ribbons"),
    path("spinners", view=ui_spinners_view, name="spinners"),
    path("tabs", view=ui_tabs_view, name="tabs"),
    path("tooltips", view=ui_tooltips_view, name="tooltips"),
    path("typography", view=ui_typography_view, name="typography"),
]

hyper/charts/models.py
from django.db import models

# Create your models here.

hyper/extended/models.py
from django.db import models

# Create your models here.

hyper/form/models.py
from django.db import models

# Create your models here.

hyper/apps/forms.py
from django import forms
from django.core.exceptions import ValidationError

from hyper.apps.constants import CATEGORY_CHOICES


class EventForm(forms.Form):
    title = forms.CharField(max_length=255, required=True)
    className = forms.ChoiceField(choices=CATEGORY_CHOICES)
    start = forms.DateTimeField(required=True)
    allDay = forms.BooleanField(required=False)
    end = forms.DateTimeField(required=False)

    def clean(self):
        cleaned_data = super().clean()
        start = cleaned_data.get("start")
        end = cleaned_data.get("end")
        if end and end < start:
            raise ValidationError("End date should be lessthen start date.")

hyper/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

hyper/apps/views.py
import json
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.views import View
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import get_object_or_404


from hyper.apps.models import Event
from hyper.apps.forms import EventForm



class EventListView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        events = Event.objects.all()
        events_dict = []
        for event in events:
            events_dict.append(event.to_dict())
        return HttpResponse(json.dumps(events_dict), content_type='application/json')

class EventCreateView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        form = EventForm(data=request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            save_data = {}
            save_data["title"] = cleaned_data.get("title")
            save_data["category"] = cleaned_data.get("className")
            save_data["start_date"] = cleaned_data.get("start")
            if cleaned_data.get("allDay", None):
                save_data["all_day"] = cleaned_data.get("allDay")
            if cleaned_data.get("end", None):
                save_data["end_date"] = cleaned_data.get("end")
            event = Event.objects.create(**save_data)
            return HttpResponse(json.dumps(event.to_dict()), content_type='application/json')
        return HttpResponseBadRequest(json.dumps(form.errors), content_type='application/json')

class EventUpdateView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get("pk", None)
        obj = get_object_or_404(Event, id=pk)
        form = EventForm(data=request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            obj.title = cleaned_data.get("title")
            obj.category = cleaned_data.get("className")
            obj.start_date = cleaned_data.get("start")
            obj.all_day = cleaned_data.get("allDay", None)
            obj.end_date = cleaned_data.get("end", None)
            obj.save()
            return HttpResponse(json.dumps(obj.to_dict()), content_type='application/json')
        return HttpResponseBadRequest(json.dumps(form.errors), content_type='application/json')

class EventDeleteView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get("pk", None)
        obj = get_object_or_404(Event, id=pk)
        obj.delete()
        return HttpResponse(
            json.dumps({"message" : "The event has been removed successfully."}), 
            content_type='application/json'
            )        


class AppsView(LoginRequiredMixin, TemplateView):
    pass

# calendar
apps_calendar_calendar_view = AppsView.as_view(template_name="apps/calendar/calendar.html")


class AppsView(LoginRequiredMixin, TemplateView):
    pass

#chat
apps_chat_chat_view = AppsView.as_view(template_name="apps/chat/chat.html")

# email
apps_email_inbox_view = AppsView.as_view(template_name="apps/email/inbox.html")
apps_email_read_view = AppsView.as_view(template_name="apps/email/read.html")

# file manager
apps_file_manager_view = AppsView.as_view(template_name="apps/file/manager.html")

# projects
apps_projects_add_view = AppsView.as_view(template_name="apps/projects/add.html")
apps_projects_details_view = AppsView.as_view(template_name="apps/projects/details.html")
apps_projects_gantt_view = AppsView.as_view(template_name="apps/projects/gantt.html")
apps_projects_list_view = AppsView.as_view(template_name="apps/projects/list.html")

# social
apps_social_feed_view = AppsView.as_view(template_name="apps/social/feed.html")

# tasks
apps_tasks_details_view = AppsView.as_view(template_name="apps/tasks/details.html")
apps_tasks_kanban_view = AppsView.as_view(template_name="apps/tasks/kanban.html")
apps_tasks_tasks_view = AppsView.as_view(template_name="apps/tasks/tasks.html")

hyper/charts/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


class ChartsView(LoginRequiredMixin, TemplateView):
    pass



charts_sbrite_view = ChartsView.as_view(template_name="charts/brite.html")
charts_chartjs_view = ChartsView.as_view(template_name="charts/chartjs.html")
charts_sparkline_view = ChartsView.as_view(template_name="charts/sparkline.html")
charts_apex_area_view = ChartsView.as_view(template_name="charts/apex/area.html")
charts_apex_bar_view = ChartsView.as_view(template_name="charts/apex/bar.html")
charts_apex_bubble_view = ChartsView.as_view(template_name="charts/apex/bubble.html")
charts_apex_candlestick_view = ChartsView.as_view(template_name="charts/apex/candlestick.html")
charts_apex_column_view = ChartsView.as_view(template_name="charts/apex/column.html")
charts_apex_heatmap_view = ChartsView.as_view(template_name="charts/apex/heatmap.html")
charts_apex_line_view = ChartsView.as_view(template_name="charts/apex/line.html")
charts_apex_mixed_view = ChartsView.as_view(template_name="charts/apex/mixed.html")
charts_apex_pie_view = ChartsView.as_view(template_name="charts/apex/pie.html")
charts_apex_radar_view = ChartsView.as_view(template_name="charts/apex/radar.html")
charts_apex_radialbar_view = ChartsView.as_view(template_name="charts/apex/radialbar.html")
charts_apex_scatter_view = ChartsView.as_view(template_name="charts/apex/scatter.html")
charts_apex_sparklines_view = ChartsView.as_view(template_name="charts/apex/sparklines.html")

hyper/extended/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

# Create your views here.

class ExtendedView(LoginRequiredMixin, TemplateView):
    pass

extended_dragula_view = ExtendedView.as_view(template_name="extended/dragula.html")
extended_range_slider_view = ExtendedView.as_view(template_name="extended/range-slider.html")
extended_ratings_view = ExtendedView.as_view(template_name="extended/ratings.html")
extended_scrollbar_view = ExtendedView.as_view(template_name="extended/scrollbar.html")
extended_scrollspy_view = ExtendedView.as_view(template_name="extended/scrollspy.html")
extended_treeview_view = ExtendedView.as_view(template_name="extended/treeview.html")

hyper/form/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

# Create your views here.



class FormView(LoginRequiredMixin, TemplateView):
    pass

form_advanced_view = FormView.as_view(template_name="form/advanced.html")
form_editors_view = FormView.as_view(template_name="form/editors.html")
form_elements_view = FormView.as_view(template_name="form/elements.html")
form_fileuploads_view = FormView.as_view(template_name="form/fileuploads.html")
form_validation_view = FormView.as_view(template_name="form/validation.html")
form_wizard_view = FormView.as_view(template_name="form/wizard.html")

hyper/templates/partials/footer.html
{% load static i18n %}
<!-- Footer Start -->
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <script>document.write(new Date().getFullYear())</script> © Jsafe
            </div>
            <div class="col-md-6">
                <div class="text-md-end footer-links d-none d-md-block">
                    <a href="javascript: void(0);">About</a>
                    <a href="javascript: void(0);">Support</a>
                    <a href="javascript: void(0);">Contact Us</a>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- end Footer -->

hyper/templates/partials/left-sidebar.html
{% load static i18n %}
<!-- ========== Left Sidebar Start ========== -->
<div class="leftside-menu">
    
    <!-- LOGO -->
    <a href="{% url 'dashboard:info' %}" class="logo text-center logo-light">
        <span class="logo-lg">
            <img src="{% static 'images/jsafe_logo.png' %}" alt="" height="75">
        </span>
        <span class="logo-sm">
            <img src="{% static 'images/logo_sm.png' %}" alt="" height="16">
        </span>
    </a>

    <!-- LOGO -->
    <a href="{% url 'dashboard:info' %}" class="logo text-center logo-dark">
        <span class="logo-lg">
            <img src="{% static 'images/logo-dark.png' %}" alt="" height="16">
        </span>
        <span class="logo-sm">
            <img src="{% static 'images/logo_sm_dark.png' %}" alt="" height="16">
        </span>
    </a>
    
    <div class="h-100" id="leftside-menu-container" data-simplebar>

        <!--- Sidemenu -->
        <ul class="side-nav">

            <li class="side-nav-title side-nav-item">Navigation</li>
            <li class="side-nav-item">
                <a class="side-nav-link" href="/">
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="side-nav-item">
                <a class="side-nav-link" href="/dashboard/scans">
                    <span>Scan Info</span>
                </a>
            </li>
            <li class="side-nav-item">
                <a class="side-nav-link" href="/addresses">
                    <span>Addresses</span>
                </a>
            </li>
            <li class="side-nav-item">
                <a class="side-nav-link" href="/assets">
                    <span>Asset Groups</span>
                </a>
            </li>
            <li class="side-nav-item">
                <a class="side-nav-link" href="/scan">
                    <span>New Scan</span>
                </a>
            </li>

        </ul>
        <!-- End Sidebar -->

        <div class="clearfix"></div>

    </div>
    <!-- Sidebar -left -->

</div>
<!-- Left Sidebar End -->

hyper/templates/partials/title-meta.html
{% load static i18n %}
<meta charset="utf-8" />
<title>@@title | Hyper - Responsive Bootstrap 5 Admin Dashboard</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
<meta content="Coderthemes" name="author" />
<!-- App favicon -->
<link rel="shortcut icon" href="assets/images/favicon.ico">

hyper/templates/partials/topbar-dark.html
{% load static i18n %}
<!-- Topbar Start -->
<div class="navbar-custom topnav-navbar topnav-navbar-dark">
    <div class="container-fluid">

        <!-- LOGO -->
        <a href="{% url 'dashboard:index' %}" class="topnav-logo">
            <span class="topnav-logo-lg">
                <img src="{% static 'images/logo-light.png' %}" alt="" height="16">
            </span>
            <span class="topnav-logo-sm">
                <img src="{% static 'images/logo_sm.png' %}" alt="" height="16">
            </span>
        </a>

        <ul class="list-unstyled topbar-menu float-end mb-0">
            
            <li class="dropdown notification-list">
                <a class="nav-link dropdown-toggle arrow-none" data-bs-toggle="dropdown" href="#" id="topbar-notifydrop" role="button" aria-haspopup="true" aria-expanded="false">
                    <i class="dripicons-bell noti-icon"></i>
                    <span class="noti-icon-badge"></span>
                </a>
               
    
                    <!-- All-->
                    <a href="javascript:void(0);" class="dropdown-item text-center text-primary notify-item notify-all">
                        View All
                    </a>
    
                </div>
            </li>

            <li class="dropdown notification-list d-none d-sm-inline-block">
                <a class="nav-link dropdown-toggle arrow-none" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                    <i class="dripicons-view-apps noti-icon"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-end dropdown-menu-animated dropdown-lg p-0">
    
                    <div class="p-2">
                        <div class="row g-0">
                            <div class="col">
                                <a class="dropdown-icon-item" href="#">
                                    <img src="{% static 'images/brands/slack.png' %}" alt="slack">
                                    <span>Slack</span>
                                </a>
                            </div>
                            <div class="col">
                                <a class="dropdown-icon-item" href="#">
                                    <img src="{% static 'images/brands/github.png' %}" alt="Github">
                                    <span>GitHub</span>
                                </a>
                            </div>
                            <div class="col">
                                <a class="dropdown-icon-item" href="#">
                                    <img src="{% static 'images/brands/dribbble.png' %}" alt="dribbble">
                                    <span>Dribbble</span>
                                </a>
                            </div>
                        </div>
    
                        <div class="row g-0">
                            <div class="col">
                                <a class="dropdown-icon-item" href="#">
                                    <img src="{% static 'images/brands/bitbucket.png' %}" alt="bitbucket">
                                    <span>Bitbucket</span>
                                </a>
                            </div>
                            <div class="col">
                                <a class="dropdown-icon-item" href="#">
                                    <img src="{% static 'images/brands/dropbox.png' %}" alt="dropbox">
                                    <span>Dropbox</span>
                                </a>
                            </div>
                            <div class="col">
                                <a class="dropdown-icon-item" href="#">
                                    <img src="{% static 'images/brands/g-suite.png' %}" alt="G Suite">
                                    <span>G Suite</span>
                                </a>
                            </div>
                
                        </div>
                    </div>
    
                </div>
            </li>

            <li class="notification-list">
                <a class="nav-link end-bar-toggle" href="javascript: void(0);">
                    <i class="dripicons-gear noti-icon"></i>
                </a>
            </li>
    
            <li class="dropdown notification-list">
                <a class="nav-link dropdown-toggle nav-user arrow-none me-0" data-bs-toggle="dropdown" id="topbar-userdrop" href="#" role="button" aria-haspopup="true"
                    aria-expanded="false">
                    <span class="account-user-avatar"> 
                        <img src="{% static 'images/jsafe_logo.png' %}" alt="user-image" class="rounded-circle">
                    </span>
                    <span>
                        <span class="account-user-name">Dominic Keller</span>
                        <span class="account-position">Founder</span>
                    </span>
                </a>
                <div class="dropdown-menu dropdown-menu-end dropdown-menu-animated topbar-dropdown-menu profile-dropdown" aria-labelledby="topbar-userdrop">
                    <!-- item-->
                    <div class=" dropdown-header noti-title">
                        <h6 class="text-overflow m-0">Welcome !</h6>
                    </div>
    
                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <i class="mdi mdi-account-circle me-1"></i>
                        <span>My Account</span>
                    </a>
    
                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <i class="mdi mdi-account-edit me-1"></i>
                        <span>Settings</span>
                    </a>
    
                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <i class="mdi mdi-lifebuoy me-1"></i>
                        <span>Support</span>
                    </a>
    
                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <i class="mdi mdi-lock-outline me-1"></i>
                        <span>Lock Screen</span>
                    </a>
    
                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item" onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">
                        <i class="mdi mdi-logout me-1"></i>
                        <span>{% trans "Logout" %}</span>

                        <form method="post" id="logout-form" action="{% url 'account_logout' %}">
                            {% csrf_token %}
                            {% if redirect_field_value %}
                            <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                            {% endif %}
                        </form>
                    </a>
    
                </div>
            </li>

        </ul>
        <a class="button-menu-mobile disable-btn">
            <div class="lines">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </a>
        <div class="app-search dropdown">
            <form>
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search..." id="top-search">
                    <span class="mdi mdi-magnify search-icon"></span>
                    <button class="input-group-text btn-primary" type="submit">Search</button>
                </div>
            </form>
            <div class="dropdown-menu dropdown-menu-animated dropdown-lg" id="search-dropdown">
                <!-- item-->
                <div class="dropdown-header noti-title">
                    <h5 class="text-overflow mb-2">Found <span class="text-danger">17</span> results</h5>
                </div>
    
                <!-- item-->
                <a href="javascript:void(0);" class="dropdown-item notify-item">
                    <i class="uil-notes font-16 me-1"></i>
                    <span>Analytics Report</span>
                </a>
    
                <!-- item-->
                <a href="javascript:void(0);" class="dropdown-item notify-item">
                    <i class="uil-life-ring font-16 me-1"></i>
                    <span>How can I help you?</span>
                </a>
    
                <!-- item-->
                <a href="javascript:void(0);" class="dropdown-item notify-item">
                    <i class="uil-cog font-16 me-1"></i>
                    <span>User profile settings</span>
                </a>
    
                <!-- item-->
                <div class="dropdown-header noti-title">
                    <h6 class="text-overflow mb-2 text-uppercase">Users</h6>
                </div>
    
                <div class="notification-list">
                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <div class="d-flex">
                            <img class="d-flex me-2 rounded-circle" src="{% static 'images/users/avatar-2.jpg' %}" alt="Generic placeholder image" height="32">
                            <div class="w-100">
                                <h5 class="m-0 font-14">Erwin Brown</h5>
                                <span class="font-12 mb-0">UI Designer</span>
                            </div>
                        </div>
                    </a>
    
                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <div class="d-flex">
                            <img class="d-flex me-2 rounded-circle" src="{% static 'images/users/avatar-5.jpg' %}" alt="Generic placeholder image" height="32">
                            <div class="w-100">
                                <h5 class="m-0 font-14">Jacob Deo</h5>
                                <span class="font-12 mb-0">Developer</span>
                            </div>
                        </div>
                    </a>
                </div>
            </div> 
        </div>
    </div>
</div>
<!-- end Topbar -->